imports:
    - php

filter:
    paths: ["app/http/Controllers/*"]
    # excluded_paths: [vendor/*, tests/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
        analysis:
            project_setup:
                override:
                    - 'true'
    tests:
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"